### ISSUE TITLE
use look extension with  Pre-trained TensorFlow.js models

### ISSUE THREAD

**Issue by 408881465** [mit-cml/appinventor-extensions#30]
Hi there,

I want to use Look Extenxion with  [Pre-trained TensorFlow.js models](https://github.com/tensorflow/tfjs-models),for example [mobilenet model](https://github.com/tensorflow/tfjs-models/tree/master/mobilenet).
How can I do it?

BR

**Comment by ewpatton** [comment]
@408881465 The Look extension already uses Mobilenet, so if you just want to upgrade it with a newer model all you have to do is replace the existing model with the new model and update the list of files in the `@UsesAssets` annotation in Look.java.

We're working on some new developer materials to walk through how to build a TensorFlow.js extension from scratch, so you may want to keep an eye out for that. We'll announce it via the [open source development group](https://community.appinventor.mit.edu/c/open-source-development/10)

**Comment by 408881465** [comment]
@ewpatton 
Hi ewpatton,
Many thanks for your help.
Yes I want to updated it with my new model.
I retrain mobilenet model on my custom dataset according to  [tensorflow-for-poets-2](https://github.com/googlecodelabs/tensorflow-for-poets-2) repo. 

my tensorflow version is 1.15.0

```shell
python -m scripts.retrain ^
  --bottleneck_dir=./caoshu_bottlenecks ^
  --how_many_training_steps=4000 ^
  --model_dir=tf_files/models/ ^
  --summaries_dir=tf_files/training_summaries/"mobilenet_1.0_224" ^
  --output_graph=tf_files/caoshu_graph.pb ^
  --output_labels=tf_files/caoshu_labels.txt ^
  --architecture="mobilenet_1.0_224" ^
  --image_dir=./caoshu_imgs

python  scripts/quantize_graph.py ^
--input=tf_files/caoshu_graph.pb ^
--output=tf_files/quantized_graph.pb ^
--output_node_names=final_result ^
--mode=weights_rounded


tensorflowjs_converter ^
--input_format=tf_frozen_model ^
--output_node_names=final_result ^
--output_format=tfjs_graph_model ^
tf_files/quantized_graph.pb ^
tf_files/for_web
```
finally it  give me  files  in the for_web folder as below，
tensorflowjs_converter version is 1.3.2

```shell
group1-shard1of5.bin
group1-shard2of5.bin
group1-shard3of5.bin
group1-shard4of5.bin
group1-shard5of5.bin
_model.json_  (I rename  it to _weights_manifest.json_ later)
```
I replace the existing model with the new model and update the list of files in the @UsesAssets annotation in Look.java, ant extensions with no errors.

files in assets floder
```
group1-shard1of5.bin
group1-shard2of5.bin
group1-shard3of5.bin
group1-shard4of5.bin
group1-shard5of5.bin
_weights_manifest.json_ ( replace the original file with my own _as above_)
tfjs-0.12.4.js
scavenger_classes.js  (modify the classes according to  my lable file )
look.js

```
I modify Look.java  as below
```java 
@UsesAssets(fileNames = "look.html, look.js,  group1-shard1of5.bin,group1-shard2of5.bin,group1-shard3of5.bin,group1-shard4of5.bin,group1-shard5of5.bin, weights_manifest.json, scavenger_classes.js, tfjs-0.12.4.js")

``` 

But the AI 2  App  classification does not work，the APP screen just show white.

What is the problem？Thank.


BR
Tom

**Comment by 408881465** [comment]
@ewpatton 
Hi ewpatton,
Many thanks for your help.
Yes I want to updated it with my new model.
I retrain mobilenet model on my custom dataset according to  [tensorflow-for-poets-2](https://github.com/googlecodelabs/tensorflow-for-poets-2) repo. 

my tensorflow version is 1.15.0

```shell
python -m scripts.retrain ^
  --bottleneck_dir=./caoshu_bottlenecks ^
  --how_many_training_steps=4000 ^
  --model_dir=tf_files/models/ ^
  --summaries_dir=tf_files/training_summaries/"mobilenet_1.0_224" ^
  --output_graph=tf_files/caoshu_graph.pb ^
  --output_labels=tf_files/caoshu_labels.txt ^
  --architecture="mobilenet_1.0_224" ^
  --image_dir=./caoshu_imgs

python  scripts/quantize_graph.py ^
--input=tf_files/caoshu_graph.pb ^
--output=tf_files/quantized_graph.pb ^
--output_node_names=final_result ^
--mode=weights_rounded


tensorflowjs_converter ^
--input_format=tf_frozen_model ^
--output_node_names=final_result ^
--output_format=tfjs_graph_model ^
tf_files/quantized_graph.pb ^
tf_files/for_web
```
finally it  give me  files  in the for_web folder as below，
tensorflowjs_converter version is 1.3.2

```shell
group1-shard1of5.bin
group1-shard2of5.bin
group1-shard3of5.bin
group1-shard4of5.bin
group1-shard5of5.bin
_model.json_  (I rename  it to _weights_manifest.json_ later)
```
I replace the existing model with the new model and update the list of files in the @UsesAssets annotation in Look.java, ant extensions with no errors.

files in assets floder
```
group1-shard1of5.bin
group1-shard2of5.bin
group1-shard3of5.bin
group1-shard4of5.bin
group1-shard5of5.bin
_weights_manifest.json_ ( replace the original file with my own _as above_)
tfjs-0.12.4.js
scavenger_classes.js  (modify the classes according to  my lable file )
look.js

```
I modify Look.java  as below
```java 
@UsesAssets(fileNames = "look.html, look.js,  group1-shard1of5.bin,group1-shard2of5.bin,group1-shard3of5.bin,group1-shard4of5.bin,group1-shard5of5.bin, weights_manifest.json, scavenger_classes.js, tfjs-0.12.4.js")

``` 

But the AI 2  App  classification does not work，the APP screen just show white.

What is the problem？Thank.


BR
Tom

**Comment by 408881465** [comment]
@ewpatton 
Hi ewpatton,
Many thanks for your help.
Yes I want to updated it with my new model.
I retrain mobilenet model on my custom dataset according to  [tensorflow-for-poets-2](https://github.com/googlecodelabs/tensorflow-for-poets-2) repo. 

my tensorflow version is 1.15.0

```shell
python -m scripts.retrain ^
  --bottleneck_dir=./caoshu_bottlenecks ^
  --how_many_training_steps=4000 ^
  --model_dir=tf_files/models/ ^
  --summaries_dir=tf_files/training_summaries/"mobilenet_1.0_224" ^
  --output_graph=tf_files/caoshu_graph.pb ^
  --output_labels=tf_files/caoshu_labels.txt ^
  --architecture="mobilenet_1.0_224" ^
  --image_dir=./caoshu_imgs

python  scripts/quantize_graph.py ^
--input=tf_files/caoshu_graph.pb ^
--output=tf_files/quantized_graph.pb ^
--output_node_names=final_result ^
--mode=weights_rounded


tensorflowjs_converter ^
--input_format=tf_frozen_model ^
--output_node_names=final_result ^
--output_format=tfjs_graph_model ^
tf_files/quantized_graph.pb ^
tf_files/for_web
```
finally it  give me  files  in the for_web folder as below，
tensorflowjs_converter version is 1.3.2

```shell
group1-shard1of5.bin
group1-shard2of5.bin
group1-shard3of5.bin
group1-shard4of5.bin
group1-shard5of5.bin
model.json  (I rename  it to weights_manifest.json later)
```
I replace the existing model with the new model and update the list of files in the @UsesAssets annotation in Look.java, ant extensions with no errors.

files in assets floder
```
group1-shard1of5.bin
group1-shard2of5.bin
group1-shard3of5.bin
group1-shard4of5.bin
group1-shard5of5.bin
weights_manifest.json ( replace the original file with my own as above)
tfjs-0.12.4.js
scavenger_classes.js  (modify the classes according to  my lable file )
look.js

```
I modify Look.java  as below
```java 
@UsesAssets(fileNames = "look.html, look.js,  group1-shard1of5.bin,group1-shard2of5.bin,group1-shard3of5.bin,group1-shard4of5.bin,group1-shard5of5.bin, weights_manifest.json, scavenger_classes.js, tfjs-0.12.4.js")

``` 

But the AI 2  App  classification does not work，the APP screen just show white.

What is the problem？Thank.


BR
Tom

**Comment by 408881465** [comment]
> @408881465 The Look extension already uses Mobilenet, so if you just want to upgrade it with a newer model all you have to do is replace the existing model with the new model and update the list of files in the `@UsesAssets` annotation in Look.java.
> 
> We're working on some new developer materials to walk through how to build a TensorFlow.js extension from scratch, so you may want to keep an eye out for that. We'll announce it via the [open source development group](https://community.appinventor.mit.edu/c/open-source-development/10)

@ewpatton 
Hi ewpatton,
Many thanks for your help.
Yes I want to updated it with my new model.
I retrain mobilenet model on my custom dataset according to  [tensorflow-for-poets-2](https://github.com/googlecodelabs/tensorflow-for-poets-2) repo. 

my tensorflow version is 1.15.0

```shell
python -m scripts.retrain ^
  --bottleneck_dir=./caoshu_bottlenecks ^
  --how_many_training_steps=4000 ^
  --model_dir=tf_files/models/ ^
  --summaries_dir=tf_files/training_summaries/"mobilenet_1.0_224" ^
  --output_graph=tf_files/caoshu_graph.pb ^
  --output_labels=tf_files/caoshu_labels.txt ^
  --architecture="mobilenet_1.0_224" ^
  --image_dir=./caoshu_imgs

python  scripts/quantize_graph.py ^
--input=tf_files/caoshu_graph.pb ^
--output=tf_files/quantized_graph.pb ^
--output_node_names=final_result ^
--mode=weights_rounded


tensorflowjs_converter ^
--input_format=tf_frozen_model ^
--output_node_names=final_result ^
--output_format=tfjs_graph_model ^
tf_files/quantized_graph.pb ^
tf_files/for_web
```
finally it  give me  files  in the for_web folder as below，
tensorflowjs_converter version is 1.3.2

```shell
group1-shard1of5.bin
group1-shard2of5.bin
group1-shard3of5.bin
group1-shard4of5.bin
group1-shard5of5.bin
model.json (I rename  it to weights_manifest.json later)
```
I replace the existing model with the new model and update the list of files in the @UsesAssets annotation in Look.java, ant extensions with no errors.

files in assets floder
```
group1-shard1of5.bin
group1-shard2of5.bin
group1-shard3of5.bin
group1-shard4of5.bin
group1-shard5of5.bin
weights_manifest.json ( replace the original file with my own as above)
tfjs-0.12.4.js
scavenger_classes.js  (modify the classes according to  my lable file )
look.js

```
I modify Look.java  as below
```java 
@UsesAssets(fileNames = "look.html, look.js,  group1-shard1of5.bin,group1-shard2of5.bin,group1-shard3of5.bin,group1-shard4of5.bin,group1-shard5of5.bin, weights_manifest.json, scavenger_classes.js, tfjs-0.12.4.js")

``` 

But the AI 2  App  classification does not work，the APP screen just show white.

What is the problem？Thank.


BR
Tom

**Comment by ewpatton** [comment]
@408881465 Please repost this on the open source extensions category on the community site. It is not an issue with the extension but your modification thereof.

**Comment by 408881465** [comment]
> @408881465 Please repost this on the open source extensions category on the community site. It is not an issue with the extension but your modification thereof.

OK Thanks.
