### ISSUE TITLE
Cannot use PosenetTest.aia or TophatMe.aia sample apps

### ISSUE THREAD

**Issue by wr200m** [mit-cml/appinventor-extensions#31]
**Describe the bug**
I'm interested in using posenet extension supplied on this page: https://mit-cml.github.io/extensions/ and especially I would like to mark the posenet points on the camera feed. I was not able to get the canvas to overlay on top of the webviewer so I have been trying to see how the sample apps accomplish that. However, an error always comes up from ai2.appinventor.mit.edu whenever I try to load the posted sample apps.

"This project was saved with a newer version of the App Inventor system. We will attempt to load the project, but there may be compatibility issues."

ai2.appinventor.mit.edu About info:
Built: February 18 2020 Version: nb182b
Use Companion: 2.57b or 2.57bu
Target Android SDK: 28 (Android 9.0 Pie)

**Affects**
Obviously, the sample code would not load properly. Almost all the code is missing. I'm seeing a horizontal arrangement with the canvas and the webviewer side by side. So I would not be able to guess how overlay can be implemented.

- [ ] Designer
- [X] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Other... (please describe)

**Expected behavior**
Either the code should load on the production version of ai2.appinventor.mit.edu or you can show me where the beta version that is compatible with the sample apps may be so I can try it out.

**Steps to reproduce**
Download PosenetTest.aia and TophatMe.aia from https://mit-cml.github.io/extensions/ 
Load these projects into ai2.appinventor.mit.edu and you see the error message posted above.

**Comment by halatmit** [comment]
I just tried TopHatMe, both via a USB connection and by building it and running the apk file.
Both work (with a little flakiness).
In order to use this demo you should be using our test server at ai2-test.appinventor.mit.edu and you should be using the Companion associated with that build version 2.57t5u.

**Comment by wr200m** [comment]
Yep. This is working for me now. Thank you!. I was not aware of the test server. Would you share with me the scheduled release to production?

**Comment by ewpatton** [comment]
We can't give hard deadlines, but at the moment we're aiming for this functionality to be available March 27th, 2020. In the meantime, you can continue to use it on ai2-test.
