### ISSUE TITLE
PersonalAudioClassifer needs to be added to extensions page

### ISSUE THREAD

**Issue by kdclang** [mit-cml/appinventor-extensions#38]
**Describe the bug**

PersonalAudioClassifier extension only available currently to users in a project template file. Needs to be added to the extensions page for download.

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ x] Other... (please describe)

**Expected behavior**

Should be able to locate aix and import into an App Inventor project

**Steps to reproduce**

**Comment by ewpatton** [comment]
I've added the extension to the extensions list, see https://mit-cml.github.io/extensions/
