### ISSUE TITLE
Notifications and indications for BLE

### ISSUE THREAD

**Issue by DurandA** [mit-cml/appinventor-extensions#40]
The _bluetoothle_ extension doesn't seem to provide any capability to receive notifications and/or indications.

> Indications and Notifications are a way for a GATT Client to subscribe to data provided by a GATT Server. A Notification is an unacknowledged message or update while an Indication is an acknowledged message or update.

![Indication/Notification](https://community.nxp.com/t5/image/serverpage/image-id/57222iBCEBE3390A99158A/image-size/large?v=1.0&px=999)

Is there any plan to support notifications and indications?

**Comment by ewpatton** [comment]
@DurandA You use the `RegisterFor....` methods to request notifications.

**Comment by DurandA** [comment]
Thanks, it works fine.
