### ISSUE TITLE
Make sure existing micro bit projects in App Inventor work with latest micro bit version V2

### ISSUE THREAD

**Issue by ellelili2025** [mit-cml/appinventor-extensions#49]
**Describe the bug**
Test the existing micro bit button project and upgrade it to work with micro bit V2 if needed.

**Affects**

- [x] Designer
- [x] Blocks editor
- [x] Companion
- [x ] Compiled apps
- [x] Buildserver
- [x] Debugging
- [ ] Other... (please describe)
[MicrobitButton.aia.zip](https://github.com/mit-cml/appinventor-extensions/files/6862661/MicrobitButton.aia.zip)

**Steps to reproduce**

Please check this page for instructions to test the attached project.
http://iot.appinventor.mit.edu/assets/howtos/MIT_App_Inventor_Microbit_Button.pdf

**Comment by genglongling** [comment]
Finished.

**Comment by genglongling** [comment]
No problems so far.
