### ISSUE TITLE
Create a project for microbit V2 speaker. 

### ISSUE THREAD

**Issue by ellelili2025** [mit-cml/appinventor-extensions#58]
And write up the tutorial after the project is done.

**Comment by ellelili2025** [comment]
@genglongling create a PR for the code changes please.

**Comment by genglongling** [comment]
Dear Li, 
     The project and tutorial is finished.
     Thanks.
[PlayWithSound.zip](https://github.com/mit-cml/appinventor-extensions/files/7149333/PlayWithSound.zip)

Longling
